### ISSUE TITLE
Increase Horizontal Slider Limit

### ISSUE THREAD

**Issue by functionfirst** [Claromentis/cla-homepage-slider#20]
We should increase the horizontal slider limit from 5. Ideally this would be a config option but at the moment even a higher, hard-coded value would be useful for some clients.

Note: the reason for the original limit was to prevent end-users from adding too many sliders which might cause either performance issues or by causing UI problems by having too many slider 'pips' shown in the navigation.

**Comment by astax-t** [comment]
Done in 3.5.0 - number of slides is configurable within admin area for each slider
